### ISSUE TITLE
Frontend shows bio and membership status of logged-in user on all profile pages

### ISSUE THREAD

**Issue by W3D3** [dynatrace-oss/unguard#49]
Tested locally on Minikube and on AWS with the latest release 0.8.0.

**Describe the bug**
Instead of seeing other user's biography text and membership status, the frontend wrongly queries always the bio and membership status of the currently logged-in user.

This happens as the code in `src/frontend/site.js` is ignoring which user the profile page is displaying and derives the user id only using the JWT token - which will always result in the currently logged-in user id to be returned.

**To Reproduce**
Simply change your own bio text and membership status in the UI and visit any other user's profile.
Your changes are wrongfully reflected there.

**Expected behavior**
Other profile pages should display the bio text of the selected user, as well as their membership status.

**Comment by rolze** [comment]
Yep, could reproduce.
![image](https://github.com/dynatrace-oss/unguard/assets/1905145/e7387712-e8bf-404b-bbee-a3b5188ff410)
