### ISSUE TITLE
Helm installation with tracing.enabled == false spams logs with tracing errors

### ISSUE THREAD

**Issue by W3D3** [dynatrace-oss/unguard#54]
**Environment**
* Kubuntu 22.04.2 LTS x86_64
* Unguard v0.8.1

When installing unguard using the new helm method, when not specifying the tracing profile for skaffold (or just generally not setting the `tracing.enabled` helm value to true), this results in some services trying to write traces, but failing to do so due to wrong/missing config.
The observed services that spammed their logs with tracing-related error messages were:
- `microblog-service`
- `proxy-service`

**To Reproduce**
Run `skaffold run` without any arguments and observe the logs of `microblog-service` and `proxy-service`

**Expected behavior**
I would expect none of the services to attempt to write traces if `tracing.enabled` is set to false.

**Screenshots**
Logs of the `microblog-service` attempting to write traces and failing:
![image](https://github.com/dynatrace-oss/unguard/assets/1103924/7b780713-5534-4851-b8c5-8d55c7b96d61)
Logs of the `proxy-service` attempting to write traces and failing:
![image](https://github.com/dynatrace-oss/unguard/assets/1103924/4e1a2470-50ea-46e1-bf76-b556e617a050)

**Additional context**
Example from `proxy-service.yaml` shows that we do not set any tracing related env vars of `tracing.enabled` being false, which results in the default behaviour:
![image](https://github.com/dynatrace-oss/unguard/assets/1103924/81cb5d81-433c-4851-b3f0-1757485ba5a6)

**Comment by MfCrizz** [comment]
With PR #55 the expected behavior is restored.
No more tracing-related error messages:

- microblog-service
![image](https://github.com/dynatrace-oss/unguard/assets/56442772/f965f55f-9fbf-478c-b409-60a044fbe052)
- proxy-service
![image](https://github.com/dynatrace-oss/unguard/assets/56442772/d494746e-0d4a-4993-999c-26f805cbabfe)
